name: Angular + Capacitor
# Controls when the action will run. Triggers the workflow on push or cron timing
# only for the master branch
on:
  push:
    branches: [ master ]
  
  schedule:
    - cron:  '1 22 * * *'    

    # * is a special character in YAML so you have to quote this string


jobs:
  # This will build an IPA & Upload the artifact in iOS.zip
  # artifacts will be saved only for 24hrs to save the space requirments for GH Actions.
  build-ios-dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Capacitor Dev iOS
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 089867d5
          platform: iOS
          build-type: development
          certificate: ios_dev
          native-config: ios_dev
          upload-artifact: IOS
          build-stack: macOS - 2021.10
          artifact-retention-days: 1
# # custom slack action used to report in case of failure.
      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

# web build job

  build-web-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Cap web test
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 089867d5
          platform: Web
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

# Appstore iOS build that deploys the artifacts to Appstore
  build-ios-appstore-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Capacitor Appstore iOS
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 089867d5
          platform: iOS
          build-type: app-store
          certificate: ios_deploy
          native-config: ios_deploy
          destinations: Appstore
          upload-artifact: ios
          build-stack: macOS - 2021.10
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}



  build-ios-enterprise-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Capacitor Appstore iOS
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 089867d5
          platform: iOS
          build-type: enterprise
          certificate: ios_ent
          native-config: ios_ent
          upload-artifact: ios
          build-stack: macOS - 2021.10
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

  build-android-debug-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Capacitor Android debug
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 089867d5
          platform: Android
          build-type: debug
          upload-artifact: android
          build-stack: Linux - 2021.10
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

  # Release Android build that deploys the .apk to Playstore

  build-android-release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Capacitor Appstore iOS
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 089867d5
          platform: Android
          build-type: release
          certificate: prod
          destinations: Playstore
          native-config: android_deploy
          upload-artifact: android
          build-stack: Linux - 2021.10
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
